### ISSUE TITLE
Error: /Stage[main]/Jira::Install/Archive[/tmp/atlassian-jira-software-7.2.3.tar.gz]/ensure: change from absent to present failed: Download file checksum mismatch

### ISSUE THREAD

**Issue by felipe1982** [voxpupuli/puppet-jira#173] opened 2016-10-18 06:28 UTC
I am getting an error

**Error: /Stage[main]/Jira::Install/Archive[/tmp/atlassian-jira-software-7.2.3.tar.gz]/ensure: change from absent to present failed: Download file checksum mismatch**

When trying to run the below manifest on RHEL 7 Vagrant. `puppet-archive` is version 1.1.2.

``` puppet

class { 'jira':
  javahome => '/opt/java',
  db       => 'postgresql',
  version  => '7.2.3',
}
#  uses tylerwalts-jdk_oracle
include profiles::jdk8
include ::jira::facts
include ::postgresql::server
```

**Comment by dpisano** [comment] 2016-10-20 04:31
I had to add the checksum to my jira class to get it to work.

**Comment by dhoppe** [comment] 2016-10-20 05:24
I think this happens since we use archive as default, because we set `checksum` to `undef` but `checksum_verify` defaults to `true`. 

We need to set the checksum for version 6.4.1 and fix the documentation / rspec tests.

**Comment by felipe1982** [comment] 2016-10-20 05:26
How did you obtain the checksum in the first place?

**Comment by dpisano** [comment] 2016-10-20 05:28
I downloaded the archive file locally and computed the md5 checksum.

**Comment by dhoppe** [comment] 2016-10-20 05:39
Unfortunately they do not provide the checksum or a file to verify against. 
https://jira.atlassian.com/browse/JRA-60845

**Comment by felipe1982** [comment] 2016-10-20 05:41
How do we set `checksum_verify` to `false` ?

**Comment by sacres** [comment] 2016-10-20 06:33
I was wondering why I hadn't come across this nor could reproduce it. Rather than the archive module, use the deploy module (as mentioned in the [README](https://github.com/voxpupuli/puppet-jira#upgrades-to-the-jira-puppet-module) )
`deploy_module          => 'deploy',`

**Comment by sacres** [comment] 2016-10-20 06:36
Edited last comment with the _correct_ param. x_X
`deploy_module => 'staging',`

**Comment by sacres** [comment] 2016-11-05 02:17
@felipe1982 Have you resolved this as recommended?

**Comment by felipe1982** [comment] 2016-11-05 06:34
@sacres : thanks for checking in. I have not yet tried `staging`, but I do believe that this module does *not* work out of the box to install Jira.  I'll give it a try in a few weeks when I get a chance to play/use/upgrade JIRA again at my office.

Thanks.

**Comment by sacres** [comment] 2017-01-16 10:02
@felipe1982 I'm closing this as we have added patches to remedy checksum issues as well as defining the archive module as default in the code and the README.md. Feel free to reach out if you still encounter issues. Thanks!

**Closed by sacres** 2017-01-16 10:02 UTC
